spring:
  application:
    name: SpenditApi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:spendit}
  output:
    ansi:
      enabled: detect
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    enabled: false
cors:
  allowed-origins:
    - http://${DOMAIN}
    - https://${DOMAIN}
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: Authorization
  allow-credentials: true
jwt:
  secret: ${JWT_SECRET}
  jwt-expiration: 86400  # 24 hours
  refresh-expiration: 604800  # 7 days
cookies:
  domain: ${DOMAIN}
  http-only: true
  secure: false
bucket:
  serve: false
  public-root: /wwwroot/
  private-root: /bucket/
